go_import_path: orderApp/
language: go
sudo: false
go:
  - 1.6
  - tip
before_script:
  - go vet -v ./...
install:
  - go get github.com/go-sql-driver/mysql
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
script:
  - go test -v ./...
